config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "stories#index"
  resources :stories
  resources :users
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord

    validates :title, 
    presence: { message: "can't be blank" },
    length: { in: 3..30, message: "mini:3, maxi:30" },
    uniqueness: { message: "already exist" }

    validates :content, 
    presence: { message: "can't be blank" },
    length: {minimum: 10, message: "mini:10" },
    uniqueness: { message: "already exist" }

    validates :author, 
    presence: { message: "can't be blank" },
    length: { in: 3..30, message: "mini:3, maxi:30" }

    belongs_to :user
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :stories
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

    before_action :set_story, only: %i[show edit update destroy]
    before_action :authenticate_user!, except: %i[index show]

    def index
        @stories = Story.all
    end

    def show
    end

    def edit
    end

    def update 
        if @story.update(story_params)
            redirect_to root_path, notice: "Story update"
        else
            flash.now[:alert] = @story.errors.full_messages[0]
            render "edit"
        end
    end
    
    def new
        @story = Story.new
    end

    def create
        @story = Story.new(story_params)
        @story.user_id = current_user.id
        if @story.save
            redirect_to root_path, notice: "Story create"
        else
            flash.now[:alert] = @story.errors.full_messages[0]
            render "new"
        end
    end
    
    def destroy
        @story.destroy
        redirect_to root_path, notice: "Story delete"
    end

    #######
    private
    #######

    def story_params
        params.require(:story).permit(:title, :content, :author)
    end

    def set_story
        @story = Story.find(params[:id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
  
    def index
      @users=User.all
    end
  
    def show
    end
  
    def new
    end
  
    def edit
    end
  
    def destroy
      @user.destroy
      redirect_to root_path
    end
  
    #######
    private
    #######
  
    def set_user
      @user=User.find(params[:id])
    end
  
    def user_params
      params.require(:user).permit(:email, :password)
    end
  
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_banner.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!-- displays site properly based on user's device -->

      <link rel="icon" type="image/png" sizes="32x32" href="./images/favicon-32x32.png">

    <!-- CSS Styles -->
    <link rel="stylesheet" type="text/css" href="style.css" />

    <!-- Font -->


  <!-- Font awesome -->
  <script src="https://kit.fontawesome.com/8d01fb2593.js" crossorigin="anonymous"></script>

</head>

<body>

<div class="jumbotron jumbotron1-hero">
<div class="containerMain">
  <br>
  <right><h1>Top tendance du <strong>Soir</strong></h1></right>
  </div>
</div>

</body>

</html>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="container" style="padding-top: 1rem;">
    <div class="alert alert-success"><%= flash[:notice] %></div>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="container" style="padding-top: 1rem;">
    <div class="alert alert-danger"><%= flash[:alert] %></div>
  </div>
<% end %>

<% if flash[:message] %>
  <div class="alert alert-danger">
    <ul>
    <% @story.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-white text-center text-primary">

    <div class="container p-4">

      <section class="container-fluid">

        <div class="row">

          <div class="col-md-3 mb-4 mb-md-0">
            <h5 class="text-uppercase">QUI SOMMES-NOUS ?</h5>
          </div>

          <div class="col-md-3 mb-4 mb-md-0">
            <h5 class="text-uppercase">NOUS CONTACTER</h5>
          </div>

          <div class="col-md-3 mb-4 mb-md-0">
            <h5 class="text-uppercase">CONFIDENTIALITÉ</h5>
          </div>

          <div class="col-md-3 mb-4 mb-md-0">
            <h5 class="text-uppercase">MENTIONS LÉGALES</h5>
        </div>

      </section>

    </div>
    <div class="text-center p-3 bg-primary">
      <a class="text-white" href="">&copy; Les Petites Histoires du Soir - THP x Twone</a>
    </div>

  </footer>

app/views/layouts/_navbar.html.erb
<!-- Navbar content -->

<nav class="navbar navbar-dark bg-blue">
  <div class="container ">

    <a href="/" class="d-flex align-items-right col-md-3 mb-2 mb-md-0 text-white text-decoration-none"></a>
 
    <ul class="nav col-12  mb-2  mb-md-0">
      <li><a href="/" class="btn "><h2><strong> Home </strong></h2></a></li>
      <center style="margin-left:17rem;"><li><h2>Les Petites Histoires du Soir</h2></li></center>

      <div class="navy">

        <div class="dropdown ">
          <% if user_signed_in? %>
            <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">My account</button>
            <ul class="dropdown-menu dropdown-menu-white" aria-labelledby="dropdownMenuButton2">
              <li><a class="dropdown-item" href="<%=user_path(current_user.id)%>">About me</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="<%=cart_path(current_user.id)%>">My cart</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="<%=destroy_user_session_path%>" data-method='delete'>Logout</a></li>
            </ul>
          <% else %>
            <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">Connexion</button>
            <ul class="dropdown-menu dropdown-menu-white" aria-labelledby="dropdownMenuButton2">
              <li><a class="dropdown-item" href="<%=new_user_registration_path%>">Sign up</a></li> 
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="<%=new_user_session_path%>">Login</a></li> 
            </ul>
      		<%end%>
        </div>
      </div>
    </ul>

    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <title>ProjetFinal</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

  </head>

  <body>

    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash' %> 
      
    <%= yield %>
   
    <%= render 'layouts/footer' %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
   </div>
  </body>
</html>

app/views/stories/edit.html.erb
<h1>Edit story</h1>

<%= form_with( model:@story, url:story_path, method: :put, local: true) do |f| %>

  <div class="form-group">
    <label>Story title</label>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Story content</label>
    <%= f.text_area :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Story author</label>
    <%= f.text_field :author, class: "form-control" %>
  </div>

  <div class="form-group" style="padding-top: 1rem;">
    <button type="submit" class="btn btn-primary">Update</button>
  </div>
  
<% end %>

app/views/stories/index.html.erb
<hr>
<%= render 'layouts/banner' %>
<hr>
<br>
  <center><h1>Choisir son Histoires du Soir</h1></center>
<div class='containerfluid row ml-2 mr-2 d-flex justify-content-around gx-0 mb-5'>

<% @stories.each do |story| %>
    
    
    <div class="card m-4" style="width: 30rem; ">
        <center><h1 class="card-title"><%= story.title %></h1></center>
        <%= image_tag ("harry_potter.jpg") %>
        <div class="card-body">
         
            <p class="card-text"><%= story.content %></p>

            <%= link_to "Show", story_path(story), class: "btn btn-card" %>
        </div>
    </div>
    
    <% end %>
    
<div>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= form_with( model:@story, url:stories_path, method: :post, local: true) do |f| %>

  <div class="form-group">
    <label>Story title</label>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Story content</label>
    <%= f.text_area :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Story author</label>
    <%= f.text_field :author, class: "form-control" %>
  </div>

  <div class="form-group" style="padding-top: 1rem;">
    <button type="submit" class="btn btn-primary">New</button>
  </div>
  
<% end %>

app/views/stories/show.html.erb
    <p>Image : <%= @story.image_url %></p>
    <h1>Title : <%= @story.title %></h1>
    <p>Content : <%= @story.content %><p>
    <p>Author : <%= @story.author %></p>

<p>
    <a href="<%= stories_path %>" class="btn btn-primary">Back</a>
        <% if current_user %>
            <%if current_user.id == @story.user_id%>
                <a href="<%= edit_story_path %>" class="btn btn-secondary">Edit</a>
                <a href="<%= story_path %>" class="btn btn-danger" data-confirm="Are you sure?" data-method="DELETE" >Delete</a>
            <% end %>
        <% end %>
</p>

app/views/users/show.html.erb
<div class="cardProfile" style="width: 40rem;">
  <div class="card-body">

    <h3 class="card-title" style="display:flex; justify-content:center"><strong> <%= @user.email %></h3>
    </br>
    </br>
    <h4><strong>Creation date</strong></h4>
    <p class="card-text"><%= @user.created_at %></p>
    <hr>
    </br>
    <hr>
    </br>
    </br>

  </div>
</div>